name: "Deploy Image to ACR"

on:
  workflow_dispatch:   # manual trigger
    inputs:
      environment:
        description: "Environment to deploy (dev/stage/production)"
        required: true
        default: "production"
env:
  ACR_LOGIN_SERVER: ${{ secrets.ACR_LOGIN_SERVER }}
  ACR_NAME: ${{ secrets.ACR_NAME }}
  IMAGE_NAME: ${{ secrets.IMAGE_NAME }}
  IMAGE_TAG: ${{ github.sha }}

jobs:
 deploy:
   name: "App-Service Deploy"
   runs-on: ubuntu-24.04

   steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 'lts/*'
          cache: 'npm'

      - name: Install dependencies
        run: npm install

      - name: Run Lint
        run: npm run lint

      - name: Run Tests
        run: npm test

      - name: Security Audit
        run: npm run scan
        
      - name: Azure Login
        uses: azure/login@v2
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}
          enable-AzPSSession: true  
          
      - name: Verify Docker
        run: docker --version
          
      - name: Azure ACR Login
        run: az acr login --name $ACR_NAME

      # - name: Docker Login (Admin User)
      #   run: echo "${{ secrets.ACR_PASSWORD }}" | docker login ${{ env.ACR_LOGIN_SERVER }} -u ${{ secrets.ACR_USERNAME }} --password-stdin    
      
      # - name: Docker Login to ACR (AAD Token)
      #   run: |
      #     TOKEN=$(az acr login --name $ACR_NAME --expose-token --output tsv --query accessToken)
      #     echo $TOKEN | docker login $ACR_LOGIN_SERVER \
      #       -u 00000000-0000-0000-0000-000000000000 \
      #       --password-stdin

      - name: Docker Build
        run: |
          docker build \
            --build-arg NODE_ENV=production \
            -t $ACR_LOGIN_SERVER/$IMAGE_NAME:$IMAGE_TAG \
            -t $ACR_LOGIN_SERVER/$IMAGE_NAME:latest .

      - name: Docker Push
        run: |
          docker push $ACR_LOGIN_SERVER/$IMAGE_NAME:$IMAGE_TAG
          docker push $ACR_LOGIN_SERVER/$IMAGE_NAME:latest
          
          
      # - name: Deploy to Azure Web App
      #   uses: azure/webapps-deploy@v3
      #   with:
      #     app-name: ${{ secrets.APP_NAME }}
      #     package: .
